JU-DEV-Bootcamps/ERAS-FE

- src/app/features/reports/heat-map.component.css
- src/app/features/reports/heat-map.component.ts
> fix(heat-map): hide dummy data, update select background color

- LICENSE
> Added license to make repo public

- src/app/features/list-students-by-poll/list-students-by-poll.component.html
- src/app/features/list-students-by-poll/list-students-by-poll.component.scss
- src/app/features/list-students-by-poll/list-students-by-poll.component.ts
- src/app/shared/components/table/table.component.html
- src/app/shared/components/table/table.component.scss
- src/app/shared/components/table/table.component.spec.ts
- src/app/shared/components/table/table.component.ts
Create a component to display lists and it will be reusable
> feat: create a component for display lists

- src/app/core/constants/heat-map.ts
- src/app/core/constants/pagination.ts
- src/app/core/services/heat-map.service.ts
- src/app/features/heat-map/modal-risk-students-detail/modal-risk-students-detail.component.html
- src/app/features/heat-map/modal-risk-students-detail/modal-risk-students-detail.component.scss
- src/app/features/heat-map/modal-risk-students-detail/modal-risk-students-detail.component.ts
- src/app/features/reports/heat-map.component.css
- src/app/features/reports/heat-map.component.html
- src/app/features/reports/heat-map.component.ts
Update view risk student detail by component
> Update/eras fe 74/heatmap details by component

- src/app/core/constants/messages.ts
- src/app/core/services/Types/cosmicLattePollImportList.ts
- src/app/core/services/cosmic-latte.service.ts
- src/app/core/services/poll.service.ts
- src/app/features/cosmic-latte/cosmic-latte.component.ts
- src/app/features/import-answers-preview/import-answers-preview.component.html
- src/app/features/import-answers-preview/import-answers-preview.component.scss
- src/app/features/import-answers-preview/import-answers-preview.component.spec.ts
- src/app/features/import-answers-preview/import-answers-preview.component.ts
- src/app/features/import-answers/import-answers.component.html
- src/app/features/import-answers/import-answers.component.spec.ts
- src/app/features/import-answers/import-answers.component.ts
- src/styles/utils/_theme-fonts.scss
This PR changes the UX/UI to split the import process in cosmic latte into two. 
First, the import is done by requesting the names of the surveys from the backend and adding them to the selector. 
Then, based on the name, we call the backend to bring us all the information for the selected survey. 
This information is shown as survey details to the user and then a list of students is shown. 
The user can then choose whether to add students or not and then save the information or on the contrary, directly cancel. 
The idea is that the user has control over the information to save.
> Feature/eras fe 113/improve ux import cosmic latte

- src/app/features/list-imported-student/list-imported-student.component.html
- src/app/features/list-imported-student/list-imported-student.component.scss
- src/app/features/list-imported-student/list-imported-student.component.ts
As a developer, I want to replace existing lists with the reusable UI component to maintain consistency in information presentation across all reports and facilitate maintenance.
> refactor: update table import students with component diplay list

- src/app/features/home/home.component.html
- src/app/shared/components/charts/abstract-chart.ts
- src/app/shared/components/charts/bar-chart/bar-chart.component.ts
- src/app/shared/components/charts/pie-chart/pie-chart.component.ts
> fix: shared charts accept data

- src/app/features/home/home.component.css
- src/app/features/home/home.component.html
- src/app/features/list-poll-instances-by-filters/list-poll-instances-by-filters.component.html
Henry suggestions to improve cosmetics in home.
> cosmetic improvements

- src/app/features/reports/heat-map.component.css
- src/app/features/reports/heat-map.component.html
- src/app/features/reports/heat-map.component.ts
Correct the heat map color and create validation for PDF download.
> fix: correct the heat map color and create validation for pdf download

- src/app/features/import-students/import-students.component.ts
This fix refresh of imports csv table
> fix import students csv, refresh table

- src/app/features/cosmic-latte/cosmic-latte.component.css
- src/app/features/home/home.component.css
- src/styles/utils/_theme-colors.scss
- src/styles/utils/_theme-components.scss
> Refactor/eras fe/improve styles

- src/app/features/cohort/cohort/cohort.component.html
- src/app/features/evaluation-process/evaluation-process-list/evaluation-process-list.component.html
- src/app/features/import-answers/import-answers.component.html
- src/app/features/list-students-by-poll/list-students-by-poll.component.html
- src/app/features/reports/heat-map.component.html
- src/app/shared/components/layout/layout.component.html
- src/app/shared/components/layout/layout.component.ts
- src/app/shared/components/student-risklevel-table/student-risklevel-table.component.html
- src/app/shared/components/student-risklevel-table/student-risklevel-table.component.ts
Update layout menu with latest features and titles
> refactor: update layout menu and titles

- src/app/features/reports/heat-map.component.ts
[ERAS114](https://github.com/JU-DEV-Bootcamps/ERAS/issues/114)
> fix(ERAS114): bug solved changed the way to get the x value from the data series

- src/app/shared/components/layout/layout.component.html
Moved the "Polls Answered" to the reports section
[ERAS-116](https://github.com/JU-DEV-Bootcamps/ERAS/issues/116)
> refactor(ERAS-116): moved the polls answered to the reports section

- src/app/features/list-students-by-poll/list-students-by-poll.component.html
- src/app/features/list-students-by-poll/list-students-by-poll.component.ts
- src/app/shared/components/layout/layout.component.html
Removed Unused Select and changed service method to getAll
https://github.com/JU-DEV-Bootcamps/ERAS/issues/119
> Change student list to all studentds instead of by poll

- src/app/app.routes.ts
- src/app/core/constants/riskLevel.ts
- src/app/features/evaluation-process/evaluation-process-form/evaluation-process-form.component.ts
- src/app/features/import-answers/import-answers.component.css
- src/app/features/reports/heat-map.component.html
- src/app/features/reports/heat-map.component.ts
- src/app/features/reports/types/data.generator.d.ts
- src/app/features/risk-students/risk-students.component.html
- src/app/features/risk-students/risk-students.component.spec.ts
- src/app/features/risk-students/risk-students.component.ts
- src/app/shared/components/charts/abstract-chart.ts
- src/app/shared/components/charts/bar-chart/bar-chart.component.ts
- src/app/shared/components/layout/layout.component.html
- src/app/shared/components/risk-students-table/risk-students-table.component.html
- src/app/shared/components/risk-students-table/risk-students-table.component.scss
- src/app/shared/components/risk-students-table/risk-students-table.component.ts
- src/app/shared/components/student-risklevel-table/student-risklevel-table.component.spec.ts
Poll Heatmap: Remove Student And their Risk Level and move to another report view
> Refactor/eras fe 113/move risk students

- src/app/core/models/HeatmapSummaryModel.ts
- src/app/core/services/heat-map.service.ts
- src/app/features/cohort/students-risk/students-risk.component.ts
- src/app/features/list-poll-instances-by-filters/list-poll-instances-by-filters.component.html
- src/app/features/list-poll-instances-by-filters/list-poll-instances-by-filters.component.spec.ts
- src/app/features/list-poll-instances-by-filters/list-poll-instances-by-filters.component.ts
- src/app/features/reports/constants/heat-map.ts
- src/app/features/reports/heat-map/heat-map.component.ts
- src/app/features/reports/summary-heatmap/summary-heatmap.component.ts
- src/app/shared/components/risk-students-table/risk-students-table.component.spec.ts
Updated hatmap summary to match latest changes in ERAS
> test: updated tests to reflect changes

- src/app/core/services/Types/cosmicLattePollImportList.ts
- src/app/core/services/Types/page.type.ts
- src/app/core/services/Types/server.type.ts
- src/app/core/services/Types/student.type.ts
- src/app/core/services/csv-checker.service.ts
- src/app/core/services/import-students.service.ts
- src/app/core/services/poll-instance.service.ts
- src/app/core/services/poll.service.ts
- src/app/features/import-answers-preview/import-answers-preview.component.ts
- src/app/features/import-answers/import-answers.component.ts
- src/app/features/import-students/import-students.component.ts
- src/app/features/list-imported-student/list-imported-student.component.ts
- src/app/features/list-students-by-poll/list-students-by-poll.component.ts
- src/app/features/reports/heat-map/heat-map.component.spec.ts
- src/app/features/reports/util/data.adapter.ts
- src/app/shared/components/table/table.component.html
- src/app/shared/components/table/table.component.spec.ts
- src/app/shared/components/table/table.component.ts
42 current eslint disable comments in total.
Removed 14 and replace them for proper TS interfaces.
Now there should be only 28:
> Cleanup/eras 127/elint disable

- src/app/shared/components/layout/layout.component.html
menu labels changed
[ERAS-FE#199](https://github.com/JU-DEV-Bootcamps/ERAS-FE/issues/199)
> refactor(ERAS-FE-199): menu labels changed

- src/app/features/cohort/students-risk/students-risk.component.html
- src/app/features/cohort/students-risk/students-risk.component.ts
- src/app/features/evaluation-process/evaluation-process-list/evaluation-process-list.component.html
- src/app/features/evaluation-process/evaluation-process-list/evaluation-process-list.component.scss
- src/app/features/evaluation-process/evaluation-process-list/evaluation-process-list.component.ts
- src/app/features/list-poll-instances-by-filters/list-poll-instances-by-filters.component.html
- src/app/features/list-poll-instances-by-filters/list-poll-instances-by-filters.component.ts
- src/app/features/reports/heat-map/heat-map.component.html
- src/app/features/reports/heat-map/heat-map.component.ts
- src/app/shared/components/empty-data/empty-data.component.css
- src/app/shared/components/empty-data/empty-data.component.html
- src/app/shared/components/empty-data/empty-data.component.spec.ts
- src/app/shared/components/empty-data/empty-data.component.ts
> Feature/eras fe 203/empty data component

- src/app/core/models/poll-request.model.ts
- src/app/features/cohort/util/heat-map-config.ts
- src/app/features/cosmic-latte/cosmic-latte.component.ts
- src/app/features/evaluation-process/evaluation-process-form/evaluation-process-form.component.ts
- src/app/features/evaluation-process/evaluation-process-list/evaluation-process-list.component.html
- src/app/features/evaluation-process/evaluation-process-list/evaluation-process-list.component.ts
- src/app/features/import-answers-preview/import-answers-preview.component.ts
- src/app/features/list-poll-instances-by-filters/list-poll-instances-by-filters.component.ts
- src/app/features/reports/constants/heat-map.ts
- src/app/features/reports/heat-map.component.ts
- src/app/features/reports/util/data.adapter.ts
- src/app/features/student-detail/student-detail.component.ts
- src/app/features/student/student-detail-option/student-detail-option.component.ts
- src/app/shared/components/charts/abstract-chart.ts
- src/app/shared/components/modal-dialog/modal-dialog.component.ts
- src/app/shared/components/table-with-actions/table-with-actions.component.spec.ts
Removed and cleanly replaced 26 eslint-disable all over the features and shared folders.
> chore(features, shared): removed 26 eslint-disables

- src/app/features/import-answers-preview/import-answers-preview.component.html
- src/app/features/import-answers-preview/import-answers-preview.component.scss
- src/app/features/import-answers-preview/import-answers-preview.component.ts
- src/app/features/import-answers/import-answers.component.css
fix: updated css files to implement correct button styles; corrected handle all checkbox
> fix: updated css files to implement correct button styles

- src/app/features/home/home.component.html
removed the cohorts card, the update to the services is not needed as those are working as expected
[ERAS-FE: #194 ](https://github.com/JU-DEV-Bootcamps/ERAS-FE/issues/194)
> refactor(ERAS-194): removed the cohorts card

- src/app/features/student/student-detail-option/student-detail-option.component.html
- src/app/features/student/student-detail-option/student-detail-option.component.ts
implemented a select to filter the top students at risk
[ERAS-FE#197](https://github.com/JU-DEV-Bootcamps/ERAS-FE/issues/197)
> feat(ERAS-FE#197): implemented a select to filter the top students at risk

- src/app/features/student/student-detail-option/student-detail-option.component.html
- src/app/features/student/student-detail-option/student-detail-option.component.scss
- src/app/features/student/student-detail-option/student-detail-option.component.ts
Updated the accordion to handle and show multiple tables at the same time
[ERAS-148](https://github.com/JU-DEV-Bootcamps/ERAS/issues/148)
> Feature/eras 148/different way to show students list

- package.json
- src/app/features/reports/constants/heat-map.ts
- src/app/features/student-detail/student-detail.component.html
> fix: keycloak version; lint

- package.json
Change npm keycloak version to the exact same as jala360
> fix: exact same version of keycloak as jala360

- src/app/app.config.ts
- src/environments/environment.development.sample.ts
- src/environments/environment.production.sample.ts
- src/environments/environment.ts
> fix: removed without fetch, removed extra configs

- src/app/app.config.ts
> fix: updated check iframe false

- src/app/features/home/home.component.html
> fix: updating redirect to polls answered

- src/app/features/heat-map/modal-question-details/modal-question-details.component.spec.ts
- src/app/features/heat-map/modal-question-details/modal-question-details.component.ts
fix: corrected student detail opens modal instead of new tab
> fix: corrected student detail opens modal instead of new tab

- src/app/core/models/summary.model.ts
- src/app/features/heat-map/modal-question-details/modal-question-details.component.css
- src/app/features/heat-map/modal-question-details/modal-question-details.component.html
- src/app/features/heat-map/modal-question-details/modal-question-details.component.ts
- src/app/features/list-poll-instances-by-filters/list-poll-instances-by-filters.component.ts
- src/app/features/student/student-detail-option/student-detail-option.component.ts
- src/app/modules/reports/views/dynamic-heatmap/dynamic-heatmap.component.ts
Update api/reports/polls/top report endpoints to use report view
> refactor: update report service and component for at-risk student

- src/app/app.routes.ts
- src/app/core/services/breadcrumbs.service.ts
- src/app/features/student/student-detail-option/student-detail-option.component.ts
- src/app/shared/components/breadcrumb/breadcrumb.component.html
- src/app/shared/components/breadcrumb/breadcrumb.component.spec.ts
- src/app/shared/components/breadcrumb/breadcrumb.component.ts
added the direction to the link without interacting with routing
[ERAS-147](https://github.com/JU-DEV-Bootcamps/ERAS/issues/147)
> refactor(ERAS-147): added the direction to the link without interacting with routing

- src/app/core/models/poll.model.ts
- src/app/features/student-detail/student-detail.component.html
- src/app/features/student/student-detail-option/student-detail-option.component.html
- src/app/features/student/student-detail-option/student-detail-option.component.ts
- src/app/modules/reports/components/poll-filters/poll-filters.component.html
- src/app/modules/reports/components/poll-filters/poll-filters.component.ts
Updated the model to handle the version and version date, updated some components
[ERAS-151](https://github.com/JU-DEV-Bootcamps/ERAS/issues/151)
> feat(ERAS-151): updated the model to handle the version and version date, updated some components

- src/app/features/list-imported-student/list-imported-student.component.ts
- src/app/features/modal-student-detail/modal-student-detail.component.spec.ts
- src/app/shared/components/list/list.component.spec.ts
- src/app/shared/components/modal-edit-object/modal-edit-object.component.spec.ts
Just changed a column in the table but also fixed testing missing providers
[ERAS-163](https://github.com/JU-DEV-Bootcamps/ERAS/issues/163)
> Refactor/eras 163/pattern for response models

- src/app/core/constants/riskLevel.ts
- src/app/core/models/heatmap-data.model.ts
- src/app/core/services/api/report.service.ts
- src/app/features/cohort/students-risk/students-risk.component.ts
- src/app/features/cohort/util/heat-map-config.ts
- src/app/features/reports/heat-map/util/heat-map.util.ts
- src/app/features/reports/summary-heatmap/summary-heatmap.component.ts
> refactor(heat-map-serie): adding function to sort cells for a heatmap

- .github/pull_request_template.md
> Include design checklist to pull_request_template.md

- .github/workflows/RW-test-package-FE.yml
- .github/workflows/test-package-FE.yml
> Update and rename test-package-FE.yml to RW-test-package-FE.yml

- src/app/modules/lists/views/evaluation-process-list/evaluation-process-list.component.html
- src/app/modules/lists/views/evaluation-process-list/evaluation-process-list.component.ts
fix: only incomplete and not started ev lists wont show import option
> fix: only incomplete and not started ev lists wont show import option

- src/app/modules/lists/components/evaluation-process-form/evaluation-process-form.component.ts
> refactor: adding validators on evaluation process form

- src/app/core/services/api/cohort.service.ts
- src/app/core/services/api/report.service.ts
- src/app/features/heat-map/modal-question-details/modal-question-details.component.html
- src/app/features/heat-map/modal-question-details/modal-question-details.component.spec.ts
- src/app/features/heat-map/modal-question-details/modal-question-details.component.ts
- src/app/features/list-students-by-poll/list-students-by-poll.component.ts
- src/app/features/risk-students/risk-students.component.html
- src/app/features/student-detail/student-detail.component.html
- src/app/features/student-detail/student-detail.component.ts
- src/app/shared/components/risk-students-table/risk-students-table.component.html
- src/app/shared/components/risk-students-table/risk-students-table.component.ts
Updated "Answer Details" modal on /reports/dynamic-heatmap and "Student Answers" modal on /reports/polls-answered. Now paginator should work properly.
> Fix/eras fe 164/paginator student answers

- src/app/modules/reports/components/poll-filters/poll-filters.component.ts
- src/app/modules/reports/views/summary-heatmap/summary-heatmap.component.ts
> fix(PollFilters): update Variable identifier (now PollVariableId)

- src/app/core/services/api/report.service.ts
- src/app/modules/reports/views/summary-heatmap/summary-heatmap.component.spec.ts
> fix(report-service): add name key to each row

- src/app/core/services/api/student.service.ts
- src/app/modules/reports/views/polls-answered/polls-answered.component.ts
Hi team,
Added sort to certain places, at some of them I put a TODO comment in order to be removed in the future, cause I've considered that once we get an ordered by column on the tables those should be removed or if the data comes already ordered from the backend.
Please, give it a check. thanks
- [ X ] Bug fix
- [ X ] Is the code easy to read?
- [ X ] Is the code formatted correctly?
> fix(ERAS-254): fixed ordered list alphabetically

- src/app/core/models/heatmap-data.model.ts
- src/app/core/models/reports/reports-data.model.ts
- src/app/core/services/api/heat-map.service.ts
- src/app/core/services/api/report.service.ts
- src/app/features/reports/summary-heatmap/summary-heatmap.component.ts
- src/app/modules/reports/views/dynamic-heatmap/dynamic-heatmap.component.ts
- src/app/modules/reports/views/summary-heatmap/summary-heatmap.component.spec.ts
- src/app/modules/reports/views/summary-heatmap/summary-heatmap.component.ts
Fixed [#286](https://github.com/JU-DEV-Bootcamps/ERAS/issues/286)
> Fix/eras 286/hm high values

- src/app/shared/components/layout/layout.component.html
- src/app/shared/components/layout/layout.component.scss
- src/app/shared/components/layout/layout.component.ts
- src/app/shared/components/layout/menu-item/menu-item.component.html
- src/app/shared/components/layout/menu-item/menu-item.component.ts
- src/app/shared/components/layout/menu-section/menu-section.component.html
- src/app/shared/components/layout/menu-section/menu-section.component.ts
- src/index.html
Hi team please give them a  check
-Fixed sidebar menu overlaping
-Added icons outlined support(Nice to have)
-Fixed horizontal scroll width automatically tied to case ERAS-531
Thanks!!!
- [ x ] Bug fix
- [ x ] Refactor
- [ x ] Have the requirements been met?
- [ x ] Is the code easy to read?
- [ x ] Is the code formatted correctly?
- [ x ] Is there a consistent approach to styling (CSS, SCSS, CSS-in-JS)?
- [ x ] Are all dependencies necessary and up-to-date?
- [ x ] Most important content is be visible on all screen sizes
- [ x ] Space is properly used on all screen sizes
> fix(ERAS-207): added fix for sidebar menu overlaping and scroll

- src/app/features/cohort/util/heat-map-config.ts
- src/styles/utils/index.scss
> fix: fixing tooltip container

- src/app/features/cosmic-latte/new-configuration-modal/new-configuration-modal.component.html
- src/app/features/cosmic-latte/new-configuration-modal/new-configuration-modal.component.ts
- src/app/shared/validators/forbiden-chars.validator.ts
Applied suggested changes by QA
[ERAS-242](https://github.com/JU-DEV-Bootcamps/ERAS/issues/242)
> fix(ERAS-242): applied suggested changes by QA

- src/app/features/home/home.component.html
- src/app/features/home/home.component.scss
- src/app/features/home/home.component.ts
- src/app/features/home/summary-details/summary-details.component.html
- src/app/features/home/summary-details/summary-details.component.scss
- src/app/features/home/summary-details/summary-details.component.spec.ts
- src/app/features/home/summary-details/summary-details.component.ts
- src/app/modules/lists/views/evaluation-process-list/evaluation-process-list.component.html
- src/app/shared/components/cards/stats-card/stats-card.component.html
- src/app/shared/components/cards/stats-card/stats-card.component.scss
- src/app/shared/components/cards/stats-card/stats-card.component.spec.ts
- src/app/shared/components/cards/stats-card/stats-card.component.ts
- src/app/shared/components/empty-data/empty-data.component.html
- src/app/shared/components/empty-data/empty-data.component.ts
- src/app/shared/components/layout/layout.component.scss
- src/app/shared/components/layout/user-menu/user-menu.component.html
- src/app/shared/components/layout/user-menu/user-menu.component.scss
- src/app/shared/components/layout/user-menu/user-menu.component.ts
- src/styles/utils/_theme-fonts.scss
Hi team!
Please, I added the following here:
-Was added a reusable stats-card component. Was applied content projection approach.
-Were modified styles from Home and Layout components, to keep it responsive and follow mock up recommendations
-Were added some styles for mobiles mode.
Best
> fix(ERAS-draft): added fixes and designs according mockups

- src/app/features/home/home.component.html
Restored home page title according feedback from Luis and Jorge to keep consistency
> fix(ERAS-543): restored home page title

- src/app/features/cosmic-latte/new-configuration-modal/new-configuration-modal.component.html
- src/app/features/cosmic-latte/new-configuration-modal/new-configuration-modal.component.ts
Validator for White spaces applied
ERAS-242
> Feature/eras 242/cl configuration

- src/app/modules/reports/components/poll-filters/poll-filters.component.ts
Added empty component, every time we initiate a new service call to get polls
> fix(ERAS-344): dynamic heatmap the components selection is not restored

- src/app/modules/supports-referrals/components/referral-detail/referral-detail.component.html
- src/app/modules/supports-referrals/components/referral-detail/referral-detail.component.spec.ts
- src/app/modules/supports-referrals/models/referrals.interfaces.ts
- src/app/modules/supports-referrals/referrals.component.html
- src/app/modules/supports-referrals/services/referrals.mapper.service.ts
- src/app/modules/supports-referrals/services/referrals.service.ts
- src/app/shared/components/breadcrumb/breadcrumb.component.ts
- src/app/shared/components/buttons/eras-button/eras-button.component.ts
-Integrated fully with the service and mappers to get students as well.
> feat(ERAS-385): integration end up for add detail pages

- src/app/core/services/api/student.service.ts
- src/app/core/utilities/helpers/id-generator.ts
- src/app/modules/supports-referrals/components/referral-form/referral-form.component.html
- src/app/modules/supports-referrals/components/referral-form/referral-form.component.scss
- src/app/modules/supports-referrals/components/referral-form/referral-form.component.ts
- src/app/modules/supports-referrals/models/referrals.interfaces.ts
- src/app/modules/supports-referrals/referrals.component.html
- src/app/modules/supports-referrals/referrals.component.spec.ts
- src/app/modules/supports-referrals/referrals.component.ts
- src/app/modules/supports-referrals/resolvers/referrals.resolver.ts
- src/app/modules/supports-referrals/services/juServices.service.ts
- src/app/modules/supports-referrals/services/professionals.service.ts
- src/app/modules/supports-referrals/services/referrals.mapper.service.ts
- src/app/modules/supports-referrals/services/referrals.service.ts
- src/app/shared/components/modals/eras-modal/eras-modal.component.html
- src/app/shared/components/modals/eras-modal/eras-modal.component.scss
- src/app/shared/components/modals/eras-modal/eras-modal.interface.ts
- src/app/shared/components/modals/eras-modal/eras-modal.service.ts
- src/app/shared/components/success-fail/success-fail.component.html
- src/app/shared/components/success-fail/success-fail.component.scss
- src/app/shared/components/success-fail/success-fail.component.spec.ts
- src/app/shared/components/success-fail/success-fail.component.ts
-Added create new referral feature
-Removed double call service for remissions tied to ticket ERAS#579, reported by QA team.
-Added success message
> feat(ERAS-373): referrals create new referral view

- src/app/modules/supports-referrals/services/referrals.mapper.service.ts
Added validation to only display user owner of remissions
> feat(ERAS-371): added validation to specific user

- src/app/core/services/api/student.service.ts
Wrong position fixed for getting all students
> fix(ERAS-371): fix wrong position

- src/app/shared/components/layout/layout.component.html
- src/app/shared/components/layout/layout.component.ts
- src/main.ts
-Hide support referrals, and student monitoring sections only for production but should be able for development mode.
-I added a console to confirm production is on. Once confirmed the TODO console log should be removed.
> feat(ERAS#596): first commit - hide features from prod
